
Today's session is goingto be all about AWS Lambda.

So without makingany further Ado,

let's move on to today'sagenda to understand

what all will be covered today.

So we'll start off today'ssession by discussing

the main services in the AWScompute domain after that.

We're going to seewhy AWS Lambda is as

a separate service.

We're going to discusswhat aw is Lambda actually is

and then we'll move onto the part where we'll see

how you can use a double sLambda using the AWS sdks

once we're done with thatI'll teach You guys

how you can integrate your SDK with the Eclipse IDE?

And in the endwe'll be doing a demo.

So let me quickly show you guys

how we will be using AWS Lambdain today's demonstration.

So guys, this is a website

that I created which is hostedon the Local Host.

Now what this websitedoes is it applauds a file

onto the H3 file system nowonce the file is uploaded.

It sends me a mailregarding that now

that meal is generated by a AWS LAMBDA.

I'm not now let mequickly show you

how that mail actually looks

like so let me uploada file over here.

So let file be this I click onopen and before uploading image.

I will show you my inbox.

So as of now,


// !  AWS compute domain.

So the main services are under this domain are 
// ! EC2 
// ! elastic Beanstalkand 
// ! AWS Lambda.

Now among these three the mostimportant service is EC2 so

EC2 is basically justlike a raw server.

It is like a personal computerthat you're working

on remotely, right?

So it can install any kindof improv operating system

of your choice,

which is supported bythe AWS infrastructure

and then you can use it in any manner as you want.

You can configure it to become.

A web server.

You can configure itto become a worker

to your environment anything.

// ! ----------------------------------------------------------//
// ! service is elastic Beanstalk,

which is an automatedversion of ec2.

So with the elastic Beanstalk,

you don't get the access to the operating system,

but you still have a control over the configuration

of your system

so you can choose what kind

of instance you want to launch, right?

So elastic Beanstalk is used to deploy an application.

So basically you just upload your code and your application

is deployed on the AWS infrastructure, right.

So this is what elastic Beanstalk is all about.

// ! -------------------------------------------------//
// ! AWS Lambda service.

// So the Lambda service is again an automated version

// of ec2 wherein youdon't get the access

// to the operating system with the errors Lambda.

// You don't even havethe choice to choose what kind

// of configuration you wantwith your server, right?

// So with either plus Lambda youjust have to upload your code

// and it executes.

// It's that simplebut then why do we have?

// Have an AWS Lambda servicewhen we have elastic Beanstalk.

// So let's understand that.

// So either plus Lambdalike a told you guys.

// It is an automated version

// of easy to justlike elastic Beanstalk,

// but then with AWS Lambda,

// you can only execute background tasks, right?

// You cannot deployan application.

// // ! So either plus Lambda is not used to deploy an application.

// // ! It is used to execute background tasks.

// Other than that like I toldyou guys you don't have

// to choose the Integration

// and a double s Lambda youdon't have to choose what kind

// of servers you want on depending on your workload.

// Thus kind of configuration.

// The server configurationis assigned to you, right?

// So this is why we use AWS Lambda,

// ! ---------------------------------------------------//
// but then let's go on

// to the definition part and seewhat AWS Lambda actually is.

// // AWS Lambda -
// It's a survivalistcompute service

// because you're not choosingthe server's right.

// You're not choosing what kindof Aggression you want

// in your server?

// It's a serverlesscompute service you

// just upload your code.

// And the code is executed.

// It's that simple right

// and also like it's mentionedin the definition

// and I told you guysagain again it is used

// to execute background tasks.

// It is not used to deploy an application guys.

// This is the maindifference between

// elastic Beanstalk news12.
// ! -------------------------------------------------//
So as an architect,

you should know what the use case is

and with service will suit it better.

So Moving on now,

you've understood what AWS Lambda actually is

and why do we use it?

Right?

So let's move ahead to seehow you can use this service.

So you can use the service using the software development SDKs

which are provided by AWS.

So before moving aheadand understanding

how you can use the skills.

Let's understand what these kids are all about.

//!  So the software development SDKs basically apis

which are used by developers

to connect to the desired service at the want .

So it makes the life of the developer easy

because he can now concentrateon the logical part

of his application rather than wasting time on understanding

how you can connect this code to the service

which is there on AWS, right?

The other part is

that these sdksare used with ID.

He's right.

So currently wehave only two IDs

which are supported

that is eclipseand visual studio.

So today in this session.

I'm going to teach you guys.

Is how you can connect your SDkeys with the Eclipse IDE?

So let's do that.

So before that weare going to configure
