// What is Event ?
// ' Event is a action which is performed by user or browser

// ' Event is a notification which is generated by browser or user

let btn = document.getElementById('btn');
btn.addEventListener('click', func1){
    console.log('clicked')
}

btn.addEventListener('mousedown', func3){
    console.log('mousedown')
}

btn.addEventListener('dblclick', func2){
    console.log('dblclicked')
}

btn.addEventListener('mouseover', func4){
    let element = document.getElementById('heading');
    element.style.color = 'red';
    console.log('mouseover')
}

btn.addEventListener('mouseout', func5){
    console.log('mouseout')
}

